### ISSUE TITLE
Flesh out descriptions from content in emails

### ISSUE THREAD

**Issue by calebhearth** [calebhearth/cartographer#2]

**Comment by KyleCartmell** [comment]
Best to funnel details into docs specific to each component and leave the architectural overview really simple?

**Comment by calebhearth** [comment]
That sounds reasonable.  I was actually thinking today that what you have is a fairly good overview.  We can have links to more in depth explanations elsewhere.

Sorry I haven't gotten around to this, been busy with work and not feeling well this week.
