### ISSUE TITLE
Move documentation into wiki repository

### ISSUE THREAD

**Issue by calebhearth** [calebhearth/cartographer#3]
By moving the documentation into a wiki repository and writing it in markdown or similar, we gain the ability to link between files and the accessibility of formatted instead of plaintext.

I think that the overview you wrote could also be a good start at a README.

**Comment by KyleCartmell** [comment]
Fully agree with this change.

**Comment by calebhearth** [comment]
Did this.  Didn't really make any changes outside of reformatting things.
